apiVersion: v1
kind: Service
metadata:
  labels:
    expose: "{{ .Values.nodeExporter.service.expose }}"
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: node-exporter
  annotations:
    fabric8.io/ingress.annotations: |-
      ingress.kubernetes.io/force-ssl-redirect: {{ .Values.nodeExporter.service.forceSslRedirect }}
      kubernetes.io/ingress.class: {{ .Values.nodeExporter.service.ingressClass }}
      {{- with .Values.nodeExporter.service.annotations }}
      {{- range $key, $value := . }}
      {{ $key }}: {{ $value }}
      {{- end }}
      {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9100
    protocol: TCP
  selector:
{{ include "labels.selector" . | indent 4 }}
