apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-node-exporter
  labels:
{{ include "node-exporter.labels.stakater" . | indent 4 }}
{{ include "node-exporter.labels.chart" . | indent 4 }}